Repository siguealcongreso/sitioweb, pull requests merged in 2023-09, with the labels that each got.

#4 Agregar agenda legislativa lxiii
  .gitignore
  content/monitoreo/agenda-legislativa-lxiii.md
Labels: contenido

#6 Resolví el bug de overflow
  content/monitoreo/agenda-legislativa-lxiii.md
Labels: bug, contenido

#7 Crear una plantilla de issue para agregar contenido
  .github/ISSUE_TEMPLATE/agregar-contenido.md
  .github/pull_request_template.md
Labels: documentation

#8 Agregar facultades del congreso
  content/docs/Facultades-del-congreso.md
Labels: contenido

#10 Cree los archivos Markdown y borré el index.html y base.css
  content/acerca/_index.md
  content/acerca/base.css
  content/acerca/como-surgio-sigue-al-congreso.md
  content/acerca/en-que-creemos.md
  content/acerca/index.html
  content/acerca/introduccion.md
  content/acerca/por-que-seguir-al-congreso.md
  content/acerca/que-impulsamos.md
Labels: contenido

#13 11-crear-la-sección-trabajo
  content/acerca/trabajo.html
  content/historico/_index.md
  content/trabajo/_index.md
  content/trabajo/analisis-de-la-convocatoria-para-eleccion-consejeras-y-consejero-de-la-judicatura.md
  content/trabajo/comunicado-analisis-convocatoria-1.png
  content/trabajo/comunicado-analisis-convocatoria-2.png
  content/trabajo/comunicado-analisis-convocatoria-3.png
  content/trabajo/formacion-en-la-escuela-mexicana-para-la-participacion-ciudadana.md
  content/trabajo/judicatura-que-sirva.md
  content/trabajo/judicaturaquesirva.png
  content/trabajo/proceso-de-eleccion-de-consejeras-y-consejeros-de-la-judicatura.md
Labels: contenido

#14 Agregar manual de carolina
  content/colabora/_index.md
  content/colabora/como-escoger-una-iniciativa.md
  content/colabora/como-escribir-resumen.md
  content/colabora/manual-para-iniciativas-de-ley.pdf
  content/colabora/pasos.md
  content/colabora/portada-manual.png
Labels: contenido
